// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys

import (
	"yclw/ygpay/api/sys"
	"yclw/ygpay/internal/logic/config"
)

type ControllerV1 struct {
	ConfigService *config.Config
}

func NewV1() sys.ISysV1 {
	return &ControllerV1{
		ConfigService: config.ConfigService,
	}
}
