// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package casbin

import (
	"yclw/ygpay/api/casbin"
	casbinService "yclw/ygpay/internal/logic/casbin"
)

type ControllerV1 struct {
	CasbinService *casbinService.Casbin
}

func NewV1() casbin.ICasbinV1 {
	return &ControllerV1{
		CasbinService: casbinService.CasbinService,
	}
}
