// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"yclw/ygpay/api/user"
	"yclw/ygpay/internal/logic/config"
	"yclw/ygpay/internal/logic/login"
	"yclw/ygpay/internal/logic/member"
)

type ControllerV1 struct {
	ConfigService *config.Config
	LoginService  *login.Login
	MemberService *member.Member
}

func NewV1() user.IUserV1 {
	return &ControllerV1{
		ConfigService: config.ConfigService,
		LoginService:  login.LoginService,
		MemberService: member.MemberService,
	}
}
