// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package role

import (
	"yclw/ygpay/api/role"
)

type ControllerV1 struct{}

func NewV1() role.IRoleV1 {
	return &ControllerV1{}
}
