// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package role

import (
	"yclw/ygpay/api/role"
	apiService "yclw/ygpay/internal/logic/api"
	menuService "yclw/ygpay/internal/logic/menu"
	roleService "yclw/ygpay/internal/logic/role"
)

type ControllerV1 struct {
	RoleService *roleService.Role
	MenuService *menuService.Menu
	ApiService  *apiService.Api
}

func NewV1() role.IRoleV1 {
	return &ControllerV1{
		RoleService: roleService.RoleService,
		MenuService: menuService.MenuService,
		ApiService:  apiService.ApiService,
	}
}

type ControllerV2 struct {
	RoleService *roleService.Role
}

func NewV2() role.IRoleV2 {
	return &ControllerV2{
		RoleService: roleService.RoleService,
	}
}
