// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package api

import (
	"yclw/ygpay/api/api"
)

type ControllerV1 struct{}

func NewV1() api.IApiV1 {
	return &ControllerV1{}
}
