// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package api

import (
	"yclw/ygpay/api/api"
	apiService "yclw/ygpay/internal/logic/api"
)

type ControllerV1 struct {
	ApiService *apiService.Api
}

func NewV1() api.IApiV1 {
	return &ControllerV1{
		ApiService: apiService.ApiService,
	}
}
