// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package menu

import (
	"yclw/ygpay/api/menu"
	menuService "yclw/ygpay/internal/logic/menu"
)

type ControllerV1 struct {
	menuService *menuService.Menu
}

func NewV1() menu.IMenuV1 {
	return &ControllerV1{
		menuService: menuService.MenuService,
	}
}

type ControllerV2 struct {
	menuService *menuService.Menu
}

func NewV2() menu.IMenuV2 {
	return &ControllerV2{
		menuService: menuService.MenuService,
	}
}
