// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package login

import (
	"yclw/ygpay/api/login"
	"yclw/ygpay/internal/logic/config"
	service "yclw/ygpay/internal/logic/login"
)

type ControllerV1 struct {
	ConfigService *config.Config
	LoginService  *service.Login
}

func NewV1() login.ILoginV1 {
	return &ControllerV1{
		ConfigService: config.ConfigService,
		LoginService:  service.LoginService,
	}
}
