// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"yclw/ygpay/internal/dao/internal"
)

// apiInfoDao is the data access object for the table t_api_info.
// You can define custom methods on it to extend its functionality as needed.
type apiInfoDao struct {
	*internal.ApiInfoDao
}

var (
	// ApiInfo is a globally accessible object for table t_api_info operations.
	ApiInfo = apiInfoDao{internal.NewApiInfoDao()}
)

// Add your custom methods and functionality below.
