// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"yclw/ygpay/internal/dao/internal"
)

// attachmentDao is the data access object for the table t_attachment.
// You can define custom methods on it to extend its functionality as needed.
type attachmentDao struct {
	*internal.AttachmentDao
}

var (
	// Attachment is a globally accessible object for table t_attachment operations.
	Attachment = attachmentDao{internal.NewAttachmentDao()}
)

// Add your custom methods and functionality below.
