// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"yclw/ygpay/internal/dao/internal"
)

// casbinRuleDao is the data access object for the table t_casbin_rule.
// You can define custom methods on it to extend its functionality as needed.
type casbinRuleDao struct {
	*internal.CasbinRuleDao
}

var (
	// CasbinRule is a globally accessible object for table t_casbin_rule operations.
	CasbinRule = casbinRuleDao{internal.NewCasbinRuleDao()}
)

// Add your custom methods and functionality below.
