// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"yclw/ygpay/internal/dao/internal"
)

// dictDataDao is the data access object for the table t_dict_data.
// You can define custom methods on it to extend its functionality as needed.
type dictDataDao struct {
	*internal.DictDataDao
}

var (
	// DictData is a globally accessible object for table t_dict_data operations.
	DictData = dictDataDao{internal.NewDictDataDao()}
)

// Add your custom methods and functionality below.
