// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"yclw/ygpay/internal/dao/internal"
)

// dictTypeDao is the data access object for the table t_dict_type.
// You can define custom methods on it to extend its functionality as needed.
type dictTypeDao struct {
	*internal.DictTypeDao
}

var (
	// DictType is a globally accessible object for table t_dict_type operations.
	DictType = dictTypeDao{internal.NewDictTypeDao()}
)

// Add your custom methods and functionality below.
