// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"yclw/ygpay/internal/consts"
	"yclw/ygpay/internal/dao/internal"
	"yclw/ygpay/internal/model/entity"
)

// logLoginDao is the data access object for the table t_log_login.
// You can define custom methods on it to extend its functionality as needed.
type logLoginDao struct {
	*internal.LogLoginDao
}

var (
	// LogLogin is a globally accessible object for table t_log_login operations.
	LogLogin = logLoginDao{internal.NewLogLoginDao()}
)

// Add your custom methods and functionality below.

// FindLastByMemberId 根据用户ID查询最后登录信息
func (d *logLoginDao) FindLastByMemberId(ctx context.Context, memberId int64) (res *entity.LogLogin, err error) {
	cols := d.Columns()
	err = d.Ctx(ctx).Fields(cols.LoginTime, cols.IpAddress).Where(cols.MemberId, memberId).Where(cols.LoginStatus, consts.StatusEnabled).OrderDesc(cols.Id).Scan(&res)
	if err != nil || res == nil {
		return
	}
	return
}

// GetLoginCount 获取用户登录次数
func (d *logLoginDao) GetLoginCount(ctx context.Context, memberId int64) (count int, err error) {
	cols := d.Columns()
	count, err = d.Ctx(ctx).Where(cols.MemberId, memberId).Where(cols.LoginStatus, consts.StatusEnabled).Count()
	return
}
