// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"yclw/ygpay/internal/dao/internal"
)

// memberRoleDao is the data access object for the table t_member_role.
// You can define custom methods on it to extend its functionality as needed.
type memberRoleDao struct {
	*internal.MemberRoleDao
}

var (
	// MemberRole is a globally accessible object for table t_member_role operations.
	MemberRole = memberRoleDao{internal.NewMemberRoleDao()}
)

// Add your custom methods and functionality below.
