// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"yclw/ygpay/internal/dao/internal"
)

// memberRoleDao is the data access object for the table t_member_role.
// You can define custom methods on it to extend its functionality as needed.
type memberRoleDao struct {
	*internal.MemberRoleDao
}

var (
	// MemberRole is a globally accessible object for table t_member_role operations.
	MemberRole = memberRoleDao{internal.NewMemberRoleDao()}
)

// Add your custom methods and functionality below.

// FindRoleIdByMemberId 根据用户ID查询角色ID列表
func (d *memberRoleDao) FindRoleIdByMemberId(ctx context.Context, memberId int64) (roleId int64, err error) {
	err = d.Ctx(ctx).Where(d.Columns().MemberId, memberId).Fields(d.Columns().RoleId).Scan(&roleId)
	return
}

// FindByRoleIds 根据角色ID列表查询用户ID列表
func (d *memberRoleDao) FindUserIdsByRoleIds(ctx context.Context, roleIds []int64) (userIds []int64, err error) {
	err = d.Ctx(ctx).WhereIn(d.Columns().RoleId, roleIds).Fields(d.Columns().MemberId).Scan(&userIds)
	return
}
