// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"yclw/ygpay/internal/dao/internal"
)

// menuTreeDao is the data access object for the table t_menu_tree.
// You can define custom methods on it to extend its functionality as needed.
type menuTreeDao struct {
	*internal.MenuTreeDao
}

var (
	// MenuTree is a globally accessible object for table t_menu_tree operations.
	MenuTree = menuTreeDao{internal.NewMenuTreeDao()}
)

// Add your custom methods and functionality below.
