// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"yclw/ygpay/internal/dao/internal"
	"yclw/ygpay/util/tree"
)

// menuTreeDao is the data access object for the table t_menu_tree.
// You can define custom methods on it to extend its functionality as needed.
type menuTreeDao struct {
	*internal.MenuTreeDao
}

var (
	// MenuTree is a globally accessible object for table t_menu_tree operations.
	MenuTree = menuTreeDao{internal.NewMenuTreeDao()}
)

// Add your custom methods and functionality below.

// BuildTreeByMenuIds 根据菜单ID构建树
func (d *menuTreeDao) BuildTreeByMenuIds(ctx context.Context, menuIds []int64) (res *tree.IdTree, err error) {
	T := []tree.T{}
	cols := d.Columns()
	err = d.Ctx(ctx).WhereIn(cols.Id, menuIds).Scan(&T)
	if err != nil {
		return
	}
	T = append(T, tree.T{Id: 0, Pid: -1})
	res, err = tree.BuildTree(T, 0)
	return
}
