// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"yclw/ygpay/internal/consts"
	"yclw/ygpay/internal/dao/internal"
	"yclw/ygpay/internal/model/do"
	"yclw/ygpay/internal/model/entity"

	"github.com/gogf/gf/v2/util/gconv"
)

// menuInfoDao is the data access object for the table t_menu_info.
// You can define custom methods on it to extend its functionality as needed.
type menuInfoDao struct {
	*internal.MenuInfoDao
}

var (
	// MenuInfo is a globally accessible object for table t_menu_info operations.
	MenuInfo = menuInfoDao{internal.NewMenuInfoDao()}
)

// Add your custom methods and functionality below.

// FindEnabledByMenuIds 根据菜单ID获取菜单
func (d *menuInfoDao) FindEnabledByMenuIds(ctx context.Context, menuIds []int64) (res []*entity.MenuInfo, err error) {
	cols := d.Columns()
	err = d.Ctx(ctx).WhereIn(cols.Id, menuIds).Where(cols.Status, consts.StatusEnabled).Scan(&res)
	return
}

// FindByID 根据ID获取菜单
func (d *menuInfoDao) FindByID(ctx context.Context, id int64) (res *entity.MenuInfo, err error) {
	cols := d.Columns()
	err = d.Ctx(ctx).Where(cols.Id, id).Scan(&res)
	return
}

// FindIdByMenuUid 根据MenuUid获取菜单ID
func (d *menuInfoDao) FindIdByMenuUid(ctx context.Context, menuUid string) (res int64, err error) {
	cols := d.Columns()
	value, err := d.Ctx(ctx).Where(cols.MenuUid, menuUid).Fields(cols.Id).Value()
	if err != nil {
		return
	}
	res = value.Int64()
	return
}

// FindIdsByMenuUids 根据MenuUid列表获取菜单ID列表
func (d *menuInfoDao) FindIdsByMenuUids(ctx context.Context, menuUids []string) (res []int64, err error) {
	cols := d.Columns()
	array, err := d.Ctx(ctx).WhereIn(cols.MenuUid, menuUids).Fields(cols.Id).Array()
	if err != nil {
		return
	}
	res = gconv.Int64s(array)
	return
}

// FindUidsByMenuIds 根据菜单ID列表获取MenuUid列表
func (d *menuInfoDao) FindUidsByMenuIds(ctx context.Context, menuIds []int64) (res []string, err error) {
	cols := d.Columns()
	array, err := d.Ctx(ctx).WhereIn(cols.Id, menuIds).Fields(cols.MenuUid).Array()
	if err != nil {
		return
	}
	res = gconv.Strings(array)
	return
}

// FindByMenuUid 根据MenuUid获取菜单
func (d *menuInfoDao) FindByMenuUid(ctx context.Context, menuUid string) (res *entity.MenuInfo, err error) {
	cols := d.Columns()
	err = d.Ctx(ctx).Where(cols.MenuUid, menuUid).Scan(&res)
	return
}

// FindAll 获取所有菜单
func (d *menuInfoDao) FindAll(ctx context.Context) (res []*entity.MenuInfo, err error) {
	err = d.Ctx(ctx).Scan(&res)
	return
}

// FindWithPageAndOptions 带筛选条件的分页查询
func (d *menuInfoDao) FindWithPageAndOptions(ctx context.Context, page, pageSize int, options ...QueryOption) (res []*entity.MenuInfo, total int, err error) {

	// 基础查询模型
	model := d.Ctx(ctx)

	// 应用筛选选项
	model = applyOptions(model, options...)

	// 获取总数
	total, err = model.Count()
	if err != nil {
		return
	}

	// 默认排序 + 分页查询
	err = model.Page(page, pageSize).Scan(&res)
	return
}

// Create 创建菜单
func (d *menuInfoDao) Create(ctx context.Context, req *do.MenuInfo) (id int64, err error) {
	cols := d.Columns()
	mod, err := d.Ctx(ctx).Fields(
		cols.MenuUid,
		cols.Pid,
		cols.Type,
		cols.Name,
		cols.Path,
		cols.Title,
		cols.Icon,
		cols.Sort,
		cols.ShowParent,
		cols.ShowLink,
		cols.KeepAlive,
		cols.Redirect,
		cols.Component,
		cols.FrameSrc,
		cols.Url,
		cols.Status,
	).Data(req).OmitNil().Insert()
	if err != nil {
		return
	}
	id, err = mod.LastInsertId()
	return
}

// Update 更新菜单
func (d *menuInfoDao) Update(ctx context.Context, req *do.MenuInfo) (err error) {
	cols := d.Columns()
	_, err = d.Ctx(ctx).Where(cols.Id, req.Id).Fields(
		cols.Pid,
		cols.Type,
		cols.Name,
		cols.Path,
		cols.Title,
		cols.Icon,
		cols.Sort,
		cols.ShowParent,
		cols.ShowLink,
		cols.KeepAlive,
		cols.Redirect,
		cols.Component,
		cols.FrameSrc,
		cols.Url,
		cols.Status,
	).Data(req).OmitNil().Update()
	return
}

// UpdateByMenuUid 根据MenuUid更新菜单

func (d *menuInfoDao) UpdateByMenuUid(ctx context.Context, req *do.MenuInfo) (err error) {
	cols := d.Columns()
	_, err = d.Ctx(ctx).Where(cols.MenuUid, req.MenuUid).Fields(
		cols.Pid,
		cols.Type,
		cols.Name,
		cols.Path,
		cols.Title,
		cols.Icon,
		cols.Sort,
		cols.ShowParent,
		cols.ShowLink,
		cols.KeepAlive,
		cols.Redirect,
		cols.Component,
		cols.FrameSrc,
		cols.Url,
		cols.Status,
	).Data(req).OmitNil().Update()
	return
}

// Delete 删除菜单
func (d *menuInfoDao) Delete(ctx context.Context, id int64) (err error) {
	cols := d.Columns()
	_, err = d.Ctx(ctx).Where(cols.Id, id).Delete()
	return
}

// DeleteByMenuUid 根据MenuUid删除菜单
func (d *menuInfoDao) DeleteByMenuUid(ctx context.Context, menuUid string) (err error) {
	cols := d.Columns()
	_, err = d.Ctx(ctx).Where(cols.MenuUid, menuUid).Delete()
	return
}
