// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"yclw/ygpay/internal/dao/internal"
	"yclw/ygpay/internal/model/entity"
)

// menuInfoDao is the data access object for the table t_menu_info.
// You can define custom methods on it to extend its functionality as needed.
type menuInfoDao struct {
	*internal.MenuInfoDao
}

var (
	// MenuInfo is a globally accessible object for table t_menu_info operations.
	MenuInfo = menuInfoDao{internal.NewMenuInfoDao()}
)

// Add your custom methods and functionality below.

// FindByMenuIds 根据菜单ID获取菜单
func (d *menuInfoDao) FindByMenuIds(ctx context.Context, menuIds []int64) (res []entity.MenuInfo, err error) {
	cols := d.Columns()
	err = d.Ctx(ctx).WhereIn(cols.Id, menuIds).Scan(&res)
	return
}
