// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"yclw/ygpay/internal/dao/internal"
)

// noticeReadDao is the data access object for the table t_notice_read.
// You can define custom methods on it to extend its functionality as needed.
type noticeReadDao struct {
	*internal.NoticeReadDao
}

var (
	// NoticeRead is a globally accessible object for table t_notice_read operations.
	NoticeRead = noticeReadDao{internal.NewNoticeReadDao()}
)

// Add your custom methods and functionality below.
