// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"yclw/ygpay/internal/dao/internal"
)

// noticeInfoDao is the data access object for the table t_notice_info.
// You can define custom methods on it to extend its functionality as needed.
type noticeInfoDao struct {
	*internal.NoticeInfoDao
}

var (
	// NoticeInfo is a globally accessible object for table t_notice_info operations.
	NoticeInfo = noticeInfoDao{internal.NewNoticeInfoDao()}
)

// Add your custom methods and functionality below.
