// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"yclw/ygpay/internal/dao/internal"
	"yclw/ygpay/internal/model/do"
	"yclw/ygpay/internal/model/entity"
)

// roleInfoDao is the data access object for the table t_role_info.
// You can define custom methods on it to extend its functionality as needed.
type roleInfoDao struct {
	*internal.RoleInfoDao
}

var (
	// RoleInfo is a globally accessible object for table t_role_info operations.
	RoleInfo = roleInfoDao{internal.NewRoleInfoDao()}
)

// Add your custom methods and functionality below.

// FindByID 根据ID查询角色信息
func (d *roleInfoDao) FindByID(ctx context.Context, id int64) (role *entity.RoleInfo, err error) {
	model := d.Ctx(ctx).WherePri(id)
	err = model.Scan(&role)
	return
}

// FindByRoleIds 根据角色ID列表查询角色信息
func (d *roleInfoDao) FindByRoleIds(ctx context.Context, roleIds []int64) (roles []*entity.RoleInfo, err error) {
	err = d.Ctx(ctx).WhereIn(d.Columns().Id, roleIds).Scan(&roles)
	return
}

// FindAll 查询所有角色信息
func (d *roleInfoDao) FindAll(ctx context.Context) (roles []*entity.RoleInfo, err error) {
	err = d.Ctx(ctx).Scan(&roles)
	return
}

// Create 创建角色
func (d *roleInfoDao) Create(ctx context.Context, req *do.RoleInfo) (id int64, err error) {
	cols := d.Columns()
	mod, err := d.Ctx(ctx).Fields(
		cols.Name,
		cols.Key,
		cols.Remark,
		cols.Sort,
		cols.Status,
	).Data(req).OmitNil().Insert()
	if err != nil {
		return
	}
	id, err = mod.LastInsertId()
	return
}

// Update 更新角色
func (d *roleInfoDao) Update(ctx context.Context, req *do.RoleInfo) (err error) {
	cols := d.Columns()
	_, err = d.Ctx(ctx).Where(cols.Id, req.Id).Fields(
		cols.Name,
		cols.Key,
		cols.Remark,
		cols.Sort,
		cols.Status,
	).Data(req).OmitNil().Update()
	return
}

// FindWithPageAndOptions 带筛选条件的分页查询
func (d *roleInfoDao) FindWithPageAndOptions(ctx context.Context, page, pageSize int, options ...QueryOption) (res []*entity.RoleInfo, total int, err error) {

	// 基础查询模型
	model := d.Ctx(ctx)

	// 应用筛选选项
	model = applyOptions(model, options...)

	// 获取总数
	total, err = model.Count()
	if err != nil {
		return
	}

	// 默认排序 + 分页查询
	err = model.Page(page, pageSize).Scan(&res)
	return
}

// Delete 删除角色
func (d *roleInfoDao) Delete(ctx context.Context, id int64) (err error) {
	cols := d.Columns()
	_, err = d.Ctx(ctx).Where(cols.Id, id).Delete()
	return
}
