// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"yclw/ygpay/internal/dao/internal"
	"yclw/ygpay/internal/model/entity"
)

// roleMenuDao is the data access object for the table t_role_menu.
// You can define custom methods on it to extend its functionality as needed.
type roleMenuDao struct {
	*internal.RoleMenuDao
}

var (
	// RoleMenu is a globally accessible object for table t_role_menu operations.
	RoleMenu = roleMenuDao{internal.NewRoleMenuDao()}
)

// Add your custom methods and functionality below.

// FindMenuIdsByRoleId 根据角色ID获取菜单
func (d *roleMenuDao) FindMenuIdsByRoleId(ctx context.Context, roleId int64) (res []int64, err error) {
	cols := d.Columns()
	model := []*entity.RoleMenu{}
	err = d.Ctx(ctx).Where(cols.RoleId, roleId).Fields(cols.MenuId).Scan(&model)
	res = make([]int64, 0, len(model))
	for _, v := range model {
		res = append(res, v.MenuId)
	}
	return
}
