// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"yclw/ygpay/internal/dao/internal"
)

// roleTreeDao is the data access object for the table t_role_tree.
// You can define custom methods on it to extend its functionality as needed.
type roleTreeDao struct {
	*internal.RoleTreeDao
}

var (
	// RoleTree is a globally accessible object for table t_role_tree operations.
	RoleTree = roleTreeDao{internal.NewRoleTreeDao()}
)

// Add your custom methods and functionality below.

// FindSubRoleIds 根据角色ID递归查询所有子角色ID列表
func (d *roleTreeDao) FindSubRoleIds(ctx context.Context, roleId int64) (roleIds []int64, err error) {
	// 查询直接子角色
	var directChildIds []int64
	model := d.Ctx(ctx).Where(d.Columns().Pid, roleId)
	err = model.Scan(&directChildIds)
	if err != nil {
		return
	}

	// 将直接子角色添加到结果中
	roleIds = append(roleIds, directChildIds...)

	// 递归查询每个直接子角色的子角色
	for _, childId := range directChildIds {
		var subChildIds []int64
		subChildIds, err = d.FindSubRoleIds(ctx, childId)
		if err != nil {
			return
		}
		roleIds = append(roleIds, subChildIds...)
	}

	return
}
