// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"yclw/ygpay/internal/dao/internal"
)

// roleApiDao is the data access object for the table t_role_api.
// You can define custom methods on it to extend its functionality as needed.
type roleApiDao struct {
	*internal.RoleApiDao
}

var (
	// RoleApi is a globally accessible object for table t_role_api operations.
	RoleApi = roleApiDao{internal.NewRoleApiDao()}
)

// Add your custom methods and functionality below.
