// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"yclw/ygpay/internal/dao/internal"
	"yclw/ygpay/internal/model/entity"
)

// roleApiDao is the data access object for the table t_role_api.
// You can define custom methods on it to extend its functionality as needed.
type roleApiDao struct {
	*internal.RoleApiDao
}

var (
	// RoleApi is a globally accessible object for table t_role_api operations.
	RoleApi = roleApiDao{internal.NewRoleApiDao()}
)

// Add your custom methods and functionality below.

// FindApiIdsByRoleId 根据角色ID查询apiID列表
func (d *roleApiDao) FindApiIdsByRoleId(ctx context.Context, roleId int64) (res []int64, err error) {
	model := []*entity.RoleApi{}
	cols := d.Columns()
	err = d.Ctx(ctx).Where(cols.RoleId, roleId).Scan(&model)
	if err != nil {
		return
	}
	res = make([]int64, 0, len(model))
	for _, v := range model {
		res = append(res, v.ApiId)
	}
	return
}
