// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"yclw/ygpay/internal/dao/internal"
	"yclw/ygpay/internal/model/entity"
)

// roleInfoDao is the data access object for the table t_role_info.
// You can define custom methods on it to extend its functionality as needed.
type roleInfoDao struct {
	*internal.RoleInfoDao
}

var (
	// RoleInfo is a globally accessible object for table t_role_info operations.
	RoleInfo = roleInfoDao{internal.NewRoleInfoDao()}
)

// Add your custom methods and functionality below.

// FindByID 根据ID查询角色信息
func (d *roleInfoDao) FindByID(ctx context.Context, id int64) (role *entity.RoleInfo, err error) {
	model := d.Ctx(ctx).WherePri(id)
	err = model.Scan(&role)
	return
}
