// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"yclw/ygpay/internal/dao/internal"
	"yclw/ygpay/internal/model/do"
	"yclw/ygpay/internal/model/entity"
	"yclw/ygpay/util/tree"
)

// roleTreeDao is the data access object for the table t_role_tree.
// You can define custom methods on it to extend its functionality as needed.
type roleTreeDao struct {
	*internal.RoleTreeDao
}

var (
	// RoleTree is a globally accessible object for table t_role_tree operations.
	RoleTree = roleTreeDao{internal.NewRoleTreeDao()}
)

// Add your custom methods and functionality below.

// FindSubRoleIds 根据角色ID递归查询所有子角色ID列表
func (d *roleTreeDao) FindSubRoleIds(ctx context.Context, roleId int64) (roleIds []int64, err error) {
	// 查询直接子角色
	var directChildIds []int64
	model := d.Ctx(ctx).Where(d.Columns().Pid, roleId)
	err = model.Scan(&directChildIds)
	if err != nil {
		return
	}

	// 将直接子角色添加到结果中
	roleIds = append(roleIds, directChildIds...)

	// 递归查询每个直接子角色的子角色
	for _, childId := range directChildIds {
		var subChildIds []int64
		subChildIds, err = d.FindSubRoleIds(ctx, childId)
		if err != nil {
			return
		}
		roleIds = append(roleIds, subChildIds...)
	}

	return
}

// FindPidById 根据ID获取父ID
func (d *roleTreeDao) FindPidById(ctx context.Context, id int64) (res int64, err error) {
	model := entity.RoleTree{}
	cols := d.Columns()
	err = d.Ctx(ctx).Where(cols.Id, id).Scan(&model)
	if err != nil {
		return
	}
	res = model.Pid
	return
}

// FindAll 查询所有角色树
func (d *roleTreeDao) FindAll(ctx context.Context) (res []tree.T, err error) {
	err = d.Ctx(ctx).Scan(&res)
	return
}

// Create 创建角色树
func (d *roleTreeDao) Create(ctx context.Context, req *do.RoleTree) (id int64, err error) {
	cols := d.Columns()
	mod, err := d.Ctx(ctx).Fields(
		cols.Pid,
		cols.Id,
	).Data(req).OmitNil().Insert()
	if err != nil {
		return
	}
	id, err = mod.LastInsertId()
	return
}

// Update 更新角色树
func (d *roleTreeDao) Update(ctx context.Context, req *do.RoleTree) (err error) {
	cols := d.Columns()
	_, err = d.Ctx(ctx).Where(cols.Id, req.Id).Fields(
		cols.Pid,
		cols.Id,
	).Data(req).OmitNil().Update()
	return
}

// Delete 删除角色树
func (d *roleTreeDao) Delete(ctx context.Context, id int64) (err error) {
	cols := d.Columns()
	_, err = d.Ctx(ctx).Where(cols.Id, id).Delete()
	return
}
