// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"yclw/ygpay/internal/dao/internal"
)

// roleCasbinDao is the data access object for the table t_role_casbin.
// You can define custom methods on it to extend its functionality as needed.
type roleCasbinDao struct {
	*internal.RoleCasbinDao
}

var (
	// RoleCasbin is a globally accessible object for table t_role_casbin operations.
	RoleCasbin = roleCasbinDao{internal.NewRoleCasbinDao()}
)

// Add your custom methods and functionality below.
