// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"yclw/ygpay/internal/dao/internal"
	"yclw/ygpay/internal/model/entity"
)

// sysConfigDao is the data access object for the table t_sys_config.
// You can define custom methods on it to extend its functionality as needed.
type sysConfigDao struct {
	*internal.SysConfigDao
}

var (
	// SysConfig is a globally accessible object for table t_sys_config operations.
	SysConfig = sysConfigDao{internal.NewSysConfigDao()}
)

// Add your custom methods and functionality below.

// 获取配置
func (d *sysConfigDao) GetConfig(ctx context.Context) (res []*entity.SysConfig, err error) {
	db := d.Ctx(ctx).Where("status = ?", 1)
	err = db.Scan(&res)
	return
}

// 根据分组获取配置
func (d *sysConfigDao) GetGroupConfig(ctx context.Context, group string) (res []*entity.SysConfig, err error) {
	db := d.Ctx(ctx).Where("group = ?", group).Where("status = ?", 1)
	err = db.Scan(&res)
	return
}

// 根据key获取配置
func (d *sysConfigDao) GetConfigByKey(ctx context.Context, key string) (res *entity.SysConfig, err error) {
	db := d.Ctx(ctx).Where("key = ?", key).Where("status = ?", 1)
	err = db.Scan(&res)
	return
}
