// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package member

import (
	"yclw/ygpay/api/member"
	service "yclw/ygpay/internal/logic/member"
	roleService "yclw/ygpay/internal/logic/role"
)

type ControllerV1 struct {
	MemberService *service.Member
	RoleService   *roleService.Role
}

func NewV1() member.IMemberV1 {
	return &ControllerV1{
		MemberService: service.MemberService,
		RoleService:   roleService.RoleService,
	}
}
